server:
  port: 8002
spring:
  application:
    name: short-link-admin
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
short-link:
  group:
    #一个用户最大分组数
    max-num: 20
  flow-limit:
    #流量风控开启
    enable: true
    #时间窗口周期（s）
    time-window: 2
    #时间窗口周期内能操作api的最大次数
    max-access-count: 20